name: Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
    test-build:
        runs-on: ubuntu-latest
        steps:
          - name: ls
            run:
              echo "Hola Mundo"
              cat hola.txt

